id: P388091BF
initial_creation_type: input
source_metadata:
  title: Ethical Guidelines
  language: es
  description: 'The following texts are currently available as part of our Ethical
    Guidelines series:'
  volume:
    5b3a3ee2ac904a659b54f9ab9ca6b095:
      title: A Powerful Pith Instruction to Abstain from Tobacco, the Tenacious Demon
        Plaguing People of Degenerate Times
      parent: Abstention
    d3fe6e852ade4a2eb004285e11a5db8b:
      title: Song of Advice for Giving Up Meat Eating
      parent: Abstention
    65382ae6ad1a42df963c76f717bcfa9f:
      title: The Mirror Clearly Showing What to Adopt and Abandon
      parent: Behavioural Guidelines
    7ff4ba4739e44bab88bcd3574205d159:
      title: Drodung Monastery Guidelines
      parent: Behavioural Guidelines
    806f656ed38e4e138cc59884c2f445c0:
      title: 'The Pellucid Mirror: Behavioural Guidelines for the Saṅgha'
      parent: Behavioural Guidelines
    7ed40fd62cc44499bfddb97782a29bd9:
      title: 'The Seed of Benefit and Happiness: Behavioural Guidelines'
      parent: Behavioural Guidelines
    181578c239b14c6ca1431333e60cc1ae:
      title: A Plea to Those who Present ‘Red Offerings’ to Worldly Deities
      parent: Ethical Advice
    a2bb3365da3642fabf83967f71b0461a:
      title: Nine Considerations and Criteria for Benefiting Beings
      parent: Ethical Advice
created_at: '2022-03-01T03:40:18.760748'
last_modified_at: '2022-03-01T03:40:18.760750'
